#---------------------------------------------------------------------------
# Dockerfile to build Docker Image of NGINX WebServer with my Web Application
#
# Copyleft(c) by Denis Astahov
#---------------------------------------------------------------------------

FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY awslogo.png /usr/share/nginx/html/awslogo.png